name: aqua
description: aqua

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^0.1.1
  shelf: ^0.7.7
  open_file: ^3.0.3
  flutter_staggered_animations: "^0.1.2"
  permission_handler: "^4.4.0+hotfix.4"
  provider: ^4.3.2+2
  f_logs: ^1.2.2
  device_info: ^0.4.2+9
  shared_preferences: ^0.5.12+2
  http_parser: ">=0.0.2+2 <4.0.0"
  path: ">=1.1.0 <2.0.0"
  intl: ^0.16.1
  android_mix:
    path: plugins/android_mix
  file_utils:
    path: plugins/file_utils
  # socket_io_client: ^0.9.11
  catcher: ^0.3.17
  url_launcher: ^5.7.8
  dotted_border: ^1.0.6
  flutter_local_notifications: ^3.0.2
  flutter_secure_storage: ^3.3.5
  device_apps: ^1.2.0
  intent:
    path: plugins/intent
  photo_view:
    path: plugins/photo_view
  flutter_html: ^1.1.1
  dio: ^3.0.10
  version: ^1.2.0
  package_info: ^0.4.3
  flutter_mailer: ^1.0.0
  storage_mount_listener:
    path: plugins/storage_mount_listener
  connectivity: ^0.4.9+3
  share_extend: ^1.1.9
  quick_actions: ^0.4.0+10
  wakelock: ^0.2.1+1
  markdown_widget:
    path: plugins/markdown_weight
  flutter_glide:
    path: plugins/flutter_glide
  preload_page_view: ^0.1.4
  qr_flutter: ^3.2.0
  pure_video_player:
    path: plugins/pure_video_player
  flutter_easyrefresh: ^2.1.8
  flutter_highlight: ^0.6.0
  charset_converter: ^1.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/web/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# flutter_intl:
#   enabled: true
#   class_name: S # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: zh_Hans_CN # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
