#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=C:\my_software\software\flutter"
export "FLUTTER_APPLICATION_PATH=C:\Users\wangh\Desktop\APPS\lan_file_more\plugins\photo_manager"
export "FLUTTER_TARGET=lib\main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build\ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=C:\my_software\software\flutter\bin\cache\artifacts\engine\ios"
export "FLUTTER_BUILD_NAME=0.5.8"
export "FLUTTER_BUILD_NUMBER=0.5.8"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
